"""
YOLO segmentation.

This generates the segmented images in MASK_DIR from RAW_DIR.
"""

import os
import numpy as np
import cv2

from ultralytics import YOLO

# =========================
# CONFIG
# =========================

# Directory containing the original input images
RAW_DIR = "/home/gmartinez/AdvaBIT-Internship/flower_phenotyping/data/selected_raw/train"
# Directory where segmented images generated by YOLO will be stored
MASK_DIR = "/home/gmartinez/AdvaBIT-Internship/flower_phenotyping/data/autoencoder/train_masks"
# Path to the trained YOLO segmentation model
YOLO_WEIGHTS = "/home/gmartinez/AdvaBIT-Internship/flower_phenotyping/models/yolo/best.pt"

# Create output directory if it does not already exist
os.makedirs(MASK_DIR, exist_ok=True)


def run_segmentation():
    """
    Perform flower segmentation using a trained YOLO segmentation model.

    The generated masks are applied to the original images to remove
    background information. The resulting segmented images are saved
    and later used as input for the autoencoder.
    """

    # Load the trained YOLO segmentation model
    yolo_model = YOLO(YOLO_WEIGHTS)

    # Run inference on all images in the input directory.
    #
    # imgsz: image resolution used during inference
    # conf: confidence threshold for object detection
    # device: GPU used for prediction
    # stream: process images sequentially to reduce memory usage
    results = yolo_model.predict(
        source=RAW_DIR,
        imgsz=1024,
        conf=0.3,
        device=0,
        save=True,
        stream=True
    )

    for r in results:
        # Skip images without detected masks
        if r.orig_img is None or r.masks is None:
            continue

        stem = os.path.splitext(os.path.basename(r.path))[0]

        h, w = r.orig_shape

        # Combine all detected masks into a single segmentation mask
        combined_mask = np.zeros((h, w), dtype=np.uint8)

        for mask in r.masks.data:
            m = mask.cpu().numpy()
            m = cv2.resize(m, (w, h))
            m = (m > 0.5).astype(np.uint8)
            combined_mask = np.maximum(combined_mask, m)

        # Remove background using the predicted segmentation mask
        img = r.orig_img.copy()
        segmented = cv2.bitwise_and(img, img, mask=combined_mask)
        
        # Save segmented image
        cv2.imwrite(os.path.join(MASK_DIR, f"{stem}.png"), segmented)

    print(f"✅ YOLO segmentation done. Masks saved in: {MASK_DIR}")


if __name__ == "__main__":
    run_segmentation()
